image: docker:stable-git

stages:
  - docker
  - deploy-server

build-front:
  stage: docker
  script:
    # registry user/password : variables définies dans gitlab
    - echo "$REGISTRY_PASSWORD" | docker login reg.amoyel.fr -u "$REGISTRY_USER" --password-stdin
    - docker build -t reg.amoyel.fr/aheroin/traquenard-front ./front
    - docker push reg.amoyel.fr/aheroin/traquenard-front
  only:
    - master

build-api:
  stage: docker
  script:
    # registry user/password : variables définies dans gitlab
    - echo "$REGISTRY_PASSWORD" | docker login reg.amoyel.fr -u "$REGISTRY_USER" --password-stdin
    - docker build -t reg.amoyel.fr/aheroin/traquenard-api ./api
    - docker push reg.amoyel.fr/aheroin/traquenard-api
  only:
    - master

build-db:
  stage: docker
  script:
    # registry user/password : variables définies dans gitlab
    - echo "$REGISTRY_PASSWORD" | docker login reg.amoyel.fr -u "$REGISTRY_USER" --password-stdin
    - docker build -t reg.amoyel.fr/aheroin/traquenard-db ./database
    - docker push reg.amoyel.fr/aheroin/traquenard-db
  only:
    - master

docker-deploy:
  stage: deploy-server
  image: docker/compose
  tags:
    - deploy-server
  script:
    - docker-compose down --remove-orphans
    - docker-compose -f docker-compose-prod.yml pull
    - docker-compose -f docker-compose-prod.yml up -d  --force-recreate
  only:
    - master
