version: '3'
services:
  front:
    image: reg.amoyel.fr/aheroin/traquenard-front
    container_name: traquenard-front
    ports:
      - "81:80"
    links:
      - api

  api:
    image: reg.amoyel.fr/aheroin/traquenard-api
    container_name: traquenard-api
    ports:
      - "5000:5000"
    links:
      - mariadb

  mariadb:
    image: mariadb:10.3.27
    container_name: traquenard_db
    volumes:
      - "./volumes/db:/var/lib/mysql"
      - "./database/db-save.sql:/docker-entrypoint-initdb.d/2.sql"
    environment:
      MYSQL_DATABASE: traquenard
      MYSQL_USER: traquenard
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3310:3306"
