version: '3'
services:
  front:
    image: reg.amoyel.fr/aheroin/traquenard-front:latest
    container_name: traquenard-front
    ports:
      - "82:80"
    links:
      - api
    restart: always

  api:
    image: reg.amoyel.fr/aheroin/traquenard-api:latest
    container_name: traquenard-api
    ports:
      - "5000:5000"
    links:
      - mariadb
    restart: always

  mariadb:
    image: mariadb:10.3.27
    container_name: traquenard_db
    volumes:
      - "./volumes/db:/var/lib/mysql"
      - "./database:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_DATABASE: traquenard
      MYSQL_USER: traquenard
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3310:3306"
    restart: always
